//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.26 at 01:17:35 PM PKT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://example.com/employee", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package wsdl.schema;
